package FITBUDDY;

public class ThirdForm extends javax.swing.JFrame {
    int active;
    static String name;
  static int gender;
    /** Creates new form ThirdForm */
    public ThirdForm(String name, int gender) {
        initComponents();
        this.name= name;
        this.gender= gender;

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                         
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        NVA = new javax.swing.JRadioButton();
        LA = new javax.swing.JRadioButton();
        ACTIVE = new javax.swing.JRadioButton();
        VA = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("How Active Are You?");

        NVA.setText("Not Very Active: Spend most of the day sitting (e.g: bankteller, desk job) ");
        NVA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NVAActionPerformed(evt);
            }
        });

        LA.setText("Lightly Active: Spend a good part of the day on your feet (e.g: teacher, salesperson)");
        LA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LAActionPerformed(evt);
            }
        });

        ACTIVE.setText("Active: Spend a good part of the day doing some physical activity");
        ACTIVE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ACTIVEActionPerformed(evt);
            }
        });

        VA.setText("Very Active: Spend most of the day doing heavy physical activity");
        VA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VAActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LA)
                    .addComponent(ACTIVE)
                    .addComponent(VA))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(NVA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NVA)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LA)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ACTIVE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(VA)
                .addContainerGap(120, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                       

    private void NVAActionPerformed(java.awt.event.ActionEvent evt) {                                   
        active= 1;     
        this.setVisible(false);
        new FourthForm(name, gender).setVisible(true);// TODO add your handling code here:
    }                                   

    private void ACTIVEActionPerformed(java.awt.event.ActionEvent evt) {                                       
       active=3;
       this.setVisible(false);
        new FourthForm(name, gender).setVisible(true);// TODO add your handling code here:
    }                                     

    private void LAActionPerformed(java.awt.event.ActionEvent evt) {                                   
        active= 2;
        this.setVisible(false);
        new FourthForm(name, gender).setVisible(true);// TODO add your handling code here:
    }                                 

    private void VAActionPerformed(java.awt.event.ActionEvent evt) {                                 
        active=4;
        this.setVisible(false);
        new FourthForm(name, gender).setVisible(true);// TODO add your handling code here:
    }                                 

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThirdForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThirdForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThirdForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThirdForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ThirdForm(name, gender).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JRadioButton ACTIVE;
    private javax.swing.JRadioButton LA;
    private javax.swing.JRadioButton NVA;
    private javax.swing.JRadioButton VA;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration                   

}